"""Comprehensive unit, integration, and false-positive tests for the REACH audit stage."""

import importlib.util
from pathlib import Path
import re
import sys
import unittest
from unittest.mock import patch, MagicMock

# Ensure REPO_ROOT is in sys.path
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from skills.ai_discoverability.scripts import (
    audit_discoverability,
    DiscoverabilityAuditor,
    FindingFactory,
    HttpResponse,
    RobotsInspector,
    SitemapInspector,
    LinkExtractor,
)

DISC_ID_REGEX = re.compile(r"^DISC-[0-9]{3,4}$")


def _mock_http_response(
    url: str,
    status_code: int = 200,
    body: bytes = b"",
    headers: dict = None,
    redirect_chain: list = None,
    error: str = None,
) -> HttpResponse:
    return HttpResponse(
        requested_url=url,
        final_url=url,
        status_code=status_code,
        redirect_chain=redirect_chain or [],
        headers=headers or {"content-type": "text/html; charset=utf-8"},
        body=body,
        error=error,
    )


class TestReachAuditStage(unittest.TestCase):

    # -------------------------------------------------------------
    # 1. Target URL Validation & Normalization
    # -------------------------------------------------------------
    def test_url_normalization_variations(self):
        """Verify URL validation normalizes missing schemes and fragments."""
        valid, url, err = DiscoverabilityAuditor.validate_and_normalize_url("example.com")
        self.assertTrue(valid)
        self.assertEqual(url, "https://example.com/")

        valid, url, err = DiscoverabilityAuditor.validate_and_normalize_url("http://example.com/products#section")
        self.assertTrue(valid)
        self.assertEqual(url, "http://example.com/products")

        valid, url, err = DiscoverabilityAuditor.validate_and_normalize_url("ftp://example.com")
        self.assertFalse(valid)
        self.assertIn("Unsupported URL scheme", err)

        valid, url, err = DiscoverabilityAuditor.validate_and_normalize_url("not a url at all")
        self.assertFalse(valid)

    # -------------------------------------------------------------
    # 2. HTTP Status & Redirect Handling
    # -------------------------------------------------------------
    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_200_target_page_healthy(self, mock_fetch):
        """Verify normal 200 target page with healthy robots.txt produces zero findings."""
        def side_effect(url):
            if "robots.txt" in url:
                return _mock_http_response(url, 200, b"User-agent: *\nAllow: /\nSitemap: https://example.com/sitemap.xml")
            if "sitemap.xml" in url:
                return _mock_http_response(url, 200, b"<?xml version='1.0'?><urlset><url><loc>https://example.com/</loc></url></urlset>")
            return _mock_http_response(url, 200, b"<html><head><title>Healthy Page</title></head><body><main><h1>Healthy Page</h1><p>This is a healthy page with plenty of substantive text to ensure no false positive findings are generated by the Understnd or Read stages. It has to be long enough.</p><a href='/about'>About</a></main></body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com")

        self.assertEqual(res["status"], "success")
        self.assertEqual(len(res["findings"]), 0)

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_404_target_root_generates_critical_finding(self, mock_fetch):
        """Verify 404 response on target root page generates a critical finding."""
        mock_fetch.return_value = _mock_http_response("https://example.com", 404, b"Not Found")

        res = audit_discoverability("https://example.com")
        self.assertEqual(res["status"], "success")
        self.assertGreater(len(res["findings"]), 0)

        f_404 = [f for f in res["findings"] if f["subcategory"] == "http_accessibility"]
        self.assertTrue(any(f["severity"] == "critical" and "404" in f["title"] for f in f_404))

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_500_target_root_generates_critical_finding(self, mock_fetch):
        """Verify 500 response on target root page generates a critical finding."""
        mock_fetch.return_value = _mock_http_response("https://example.com", 500, b"Server Error")

        res = audit_discoverability("https://example.com")
        self.assertEqual(res["status"], "success")
        f_500 = [f for f in res["findings"] if f["subcategory"] == "http_accessibility"]
        self.assertTrue(any(f["severity"] == "critical" and "500" in f["title"] for f in f_500))

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_dns_network_timeout_returns_failure_envelope(self, mock_fetch):
        """Verify target connection timeout produces a clean failure envelope."""
        mock_fetch.return_value = _mock_http_response(
            "https://example.com",
            status_code=0,
            error="Network error: Connection timed out",
        )
        res = audit_discoverability("https://example.com")
        self.assertEqual(res["status"], "failure")
        self.assertIn("Connection timed out", res["error"])

    # -------------------------------------------------------------
    # 3. Redirects: Normal vs Excessive
    # -------------------------------------------------------------
    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_fp_normal_301_to_200_redirect_produces_no_finding(self, mock_fetch):
        """FALSE-POSITIVE TEST: Normal 301 -> 200 redirect must NOT produce a defect finding."""
        chain = [{"from_url": "http://example.com", "status_code": 301, "to_url": "https://example.com/"}]
        mock_fetch.return_value = _mock_http_response(
            "https://example.com/",
            status_code=200,
            body=b"<html><body>Home</body></html>",
            redirect_chain=chain,
        )

        res = audit_discoverability("http://example.com")
        self.assertEqual(res["status"], "success")
        redirect_findings = [f for f in res["findings"] if f["subcategory"] == "redirects"]
        self.assertEqual(len(redirect_findings), 0, "Normal 301 redirect must NOT produce a finding")

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_fp_multiple_redirect_hops_below_threshold(self, mock_fetch):
        """FALSE-POSITIVE TEST: 2 or 3 redirect hops below threshold must NOT produce an excessive redirect finding."""
        chain = [
            {"from_url": "http://example.com", "status_code": 301, "to_url": "https://example.com"},
            {"from_url": "https://example.com", "status_code": 302, "to_url": "https://example.com/en"},
        ]
        mock_fetch.return_value = _mock_http_response(
            "https://example.com/en",
            status_code=200,
            body=b"<html><body>Home</body></html>",
            redirect_chain=chain,
        )

        auditor = DiscoverabilityAuditor(options={"max_redirects_threshold": 3})
        res = auditor.audit("http://example.com")
        redirect_findings = [f for f in res["findings"] if f["subcategory"] == "redirects"]
        self.assertEqual(len(redirect_findings), 0)

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_excessive_redirects_triggers_finding(self, mock_fetch):
        """Verify redirect hops exceeding configured threshold generate a finding."""
        chain = [
            {"from_url": "https://example.com/1", "status_code": 301, "to_url": "https://example.com/2"},
            {"from_url": "https://example.com/2", "status_code": 301, "to_url": "https://example.com/3"},
            {"from_url": "https://example.com/3", "status_code": 301, "to_url": "https://example.com/4"},
            {"from_url": "https://example.com/4", "status_code": 301, "to_url": "https://example.com/5"},
        ]
        mock_fetch.return_value = _mock_http_response(
            "https://example.com/5",
            status_code=200,
            body=b"<html><body>Home</body></html>",
            redirect_chain=chain,
        )

        auditor = DiscoverabilityAuditor(options={"max_redirects_threshold": 3})
        res = auditor.audit("https://example.com/1")
        redirect_findings = [f for f in res["findings"] if f["subcategory"] == "redirects"]
        self.assertEqual(len(redirect_findings), 1)
        self.assertEqual(redirect_findings[0]["severity"], "medium")
        self.assertIn("4", redirect_findings[0]["evidence"])

    # -------------------------------------------------------------
    # 4. Robots.txt Parser, Semantics, & AI Bot Checks
    # -------------------------------------------------------------
    def test_robots_wildcard_allow_and_disallow(self):
        """Verify robots parser handles wildcard allow vs disallow."""
        report = RobotsInspector.parse("https://example.com/robots.txt", 200, "User-agent: *\nDisallow: /")
        allowed, group, rule = report.evaluate_bot("GPTBot", "/")
        self.assertFalse(allowed)

        report_allow = RobotsInspector.parse("https://example.com/robots.txt", 200, "User-agent: *\nAllow: /")
        allowed_w, _, _ = report_allow.evaluate_bot("GPTBot", "/")
        self.assertTrue(allowed_w)

    def test_robots_ai_specific_disallow(self):
        """Verify specific AI bot disallow overrides wildcard allow."""
        text = """
        User-agent: *
        Allow: /

        User-agent: GPTBot
        User-agent: ClaudeBot
        Disallow: /
        """
        report = RobotsInspector.parse("https://example.com/robots.txt", 200, text)

        # GPTBot and ClaudeBot are disallowed
        allowed_gpt, group_gpt, _ = report.evaluate_bot("GPTBot", "/")
        self.assertFalse(allowed_gpt)

        allowed_claude, group_claude, _ = report.evaluate_bot("ClaudeBot", "/")
        self.assertFalse(allowed_claude)

        # PerplexityBot falls back to wildcard (allowed)
        allowed_perp, group_perp, _ = report.evaluate_bot("PerplexityBot", "/")
        self.assertTrue(allowed_perp)

    def test_robots_allow_overriding_disallow_path_specificity(self):
        """Verify Allow directive overrides Disallow according to path specificity."""
        # Disallow: / but Allow: /public/
        text = """
        User-agent: *
        Disallow: /
        Allow: /public/
        """
        report = RobotsInspector.parse("https://example.com/robots.txt", 200, text)

        # Root is disallowed
        allowed_root, _, _ = report.evaluate_bot("GPTBot", "/")
        self.assertFalse(allowed_root)

        # /public/page is allowed
        allowed_pub, _, rule = report.evaluate_bot("GPTBot", "/public/page")
        self.assertTrue(allowed_pub)
        self.assertEqual(rule.rule_type, "allow")

    def test_robots_equal_length_allow_precedence(self):
        """Verify when Allow and Disallow have equal length, Allow takes precedence."""
        text = """
        User-agent: *
        Disallow: /page
        Allow: /page
        """
        report = RobotsInspector.parse("https://example.com/robots.txt", 200, text)
        allowed, _, rule = report.evaluate_bot("GPTBot", "/page")
        self.assertTrue(allowed)
        self.assertEqual(rule.rule_type, "allow")

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_fp_robots_allowing_ai_crawlers_produces_no_finding(self, mock_fetch):
        """FALSE-POSITIVE TEST: robots.txt allowing AI bots produces NO robots findings."""
        text = b"User-agent: *\nDisallow: /admin/\nDisallow: /checkout/\nUser-agent: GPTBot\nAllow: /\n"
        def side_effect(url):
            if "robots.txt" in url:
                return _mock_http_response(url, 200, text)
            return _mock_http_response(url, 200, b"<html><body>OK</body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com")
        robots_findings = [f for f in res["findings"] if f["subcategory"] == "robots"]
        self.assertEqual(len(robots_findings), 0, "Robots.txt permitting AI bots must NOT produce a defect finding")

    # -------------------------------------------------------------
    # 5. Sitemap Discovery & Validation
    # -------------------------------------------------------------
    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_fp_absent_default_sitemap_not_advertised_produces_no_finding(self, mock_fetch):
        """FALSE-POSITIVE TEST: 404 on default /sitemap.xml when NOT in robots.txt produces NO finding."""
        def side_effect(url):
            if "robots.txt" in url:
                # No sitemap declared in robots.txt
                return _mock_http_response(url, 200, b"User-agent: *\nAllow: /\n")
            if "sitemap.xml" in url:
                return _mock_http_response(url, 404, b"Not Found")
            return _mock_http_response(url, 200, b"<html><body>OK</body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com")
        sitemap_findings = [f for f in res["findings"] if f["subcategory"] == "sitemap"]
        self.assertEqual(len(sitemap_findings), 0, "Absent unadvertised sitemap must not produce a finding")

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_broken_advertised_sitemap_produces_finding(self, mock_fetch):
        """Verify sitemap advertised in robots.txt returning 404 generates a finding."""
        def side_effect(url):
            if "robots.txt" in url:
                return _mock_http_response(url, 200, b"User-agent: *\nAllow: /\nSitemap: https://example.com/broken-sitemap.xml")
            if "broken-sitemap.xml" in url:
                return _mock_http_response(url, 404, b"Not Found")
            return _mock_http_response(url, 200, b"<html><body>OK</body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com")
        sitemap_findings = [f for f in res["findings"] if f["subcategory"] == "sitemap"]
        self.assertEqual(len(sitemap_findings), 1)
        self.assertIn("broken-sitemap.xml", sitemap_findings[0]["evidence"])

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_malformed_sitemap_xml_produces_finding(self, mock_fetch):
        """Verify sitemap returning invalid XML syntax produces a finding."""
        def side_effect(url):
            if "robots.txt" in url:
                return _mock_http_response(url, 200, b"User-agent: *\nAllow: /\nSitemap: https://example.com/sitemap.xml")
            if "sitemap.xml" in url:
                return _mock_http_response(url, 200, b"<html><broken xml -- not sitemap")
            return _mock_http_response(url, 200, b"<html><body>OK</body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com")
        sitemap_findings = [f for f in res["findings"] if f["subcategory"] == "sitemap"]
        self.assertEqual(len(sitemap_findings), 1)
        self.assertIn("Malformed", sitemap_findings[0]["title"])

    # -------------------------------------------------------------
    # 6. Internal Link Extraction & Representative Page Reachability
    # -------------------------------------------------------------
    def test_link_extractor_filtering_and_normalization(self):
        """Verify link extractor extracts internal links, skips fragments and external domains."""
        html = """
        <html><body>
            <a href="/about">About Us</a>
            <a href="https://example.com/products">Products</a>
            <a href="#section">Fragment</a>
            <a href="javascript:void(0)">JS</a>
            <a href="mailto:info@example.com">Email</a>
            <a href="https://otherdomain.com/blog">External</a>
        </body></html>
        """
        data = LinkExtractor.extract_links(html, "https://example.com/")
        self.assertEqual(data["total_links_found"], 6)
        self.assertEqual(data["unique_internal_count"], 2)
        self.assertIn("https://example.com/about", data["internal_links"])
        self.assertIn("https://example.com/products", data["internal_links"])
        self.assertIn("https://otherdomain.com/blog", data["external_links"])

    def test_bounded_representative_page_selection(self):
        """Verify representative selector prioritizes keywords and enforces maximum page count."""
        links = [
            f"https://example.com/page{i}" for i in range(20)
        ] + [
            "https://example.com/about-us",
            "https://example.com/documentation",
            "https://example.com/pricing-plans",
        ]
        selected = LinkExtractor.select_representative_pages(links, "https://example.com/", max_pages=5)
        self.assertEqual(len(selected), 5)
        self.assertEqual(selected[0], "https://example.com/")
        # Keyword pages should be prioritized
        self.assertTrue(any("about" in p for p in selected))
        self.assertTrue(any("pricing" in p for p in selected))

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_broken_representative_page_detection(self, mock_fetch):
        """Verify broken secondary representative internal link (404) triggers a finding."""
        def side_effect(url):
            if "robots.txt" in url:
                return _mock_http_response(url, 200, b"User-agent: *\nAllow: /\n")
            if url == "https://example.com/":
                return _mock_http_response(url, 200, b"<html><body><a href='/broken-doc'>Docs</a></body></html>")
            if "/broken-doc" in url:
                return _mock_http_response(url, 404, b"Not Found")
            return _mock_http_response(url, 200, b"<html><body>OK</body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com/")

        self.assertEqual(res["status"], "success")
        broken_findings = [f for f in res["findings"] if f["subcategory"] == "crawlability"]
        self.assertEqual(len(broken_findings), 1)
        self.assertIn("broken-doc", broken_findings[0]["evidence"])

    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_fp_secondary_page_transient_failure_does_not_fail_audit(self, mock_fetch):
        """FALSE-POSITIVE TEST: Secondary page timeout is recorded in limitations without failing audit or creating false defect."""
        def side_effect(url):
            if "robots.txt" in url:
                return _mock_http_response(url, 200, b"User-agent: *\nAllow: /\n")
            if url == "https://example.com/":
                return _mock_http_response(url, 200, b"<html><head><title>Healthy Page</title></head><body><main><h1>Healthy Page</h1><p>This is a healthy page with plenty of substantive text to ensure no false positive findings are generated by the Understnd or Read stages. It has to be long enough.</p><a href='/about'>About</a></main></body></html>")
            if "/about" in url:
                # Transient connection timeout on secondary page
                return _mock_http_response(url, 0, error="Network error: Connection timed out")
            return _mock_http_response(url, 200, b"<html><body>OK</body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com/")

        self.assertEqual(res["status"], "success")
        # Should NOT produce broken page finding for a transient network error
        crawl_findings = [f for f in res["findings"] if f["subcategory"] == "crawlability"]
        self.assertEqual(len(crawl_findings), 0)
        # Should record diagnostic in limitations
        self.assertTrue(any("Connection timed out" in lim for lim in res["limitations"]))

    # -------------------------------------------------------------
    # 7. Finding Verification & Evidence Quality
    # -------------------------------------------------------------
    @patch("skills.ai_discoverability.scripts.audit_discoverability.HttpClient.fetch")
    def test_all_generated_findings_pass_contract_validation(self, mock_fetch):
        """Verify every finding emitted by the audit passes FindingFactory contract validation."""
        def side_effect(url):
            if "robots.txt" in url:
                # Universal disallow to produce finding
                return _mock_http_response(url, 200, b"User-agent: *\nDisallow: /\nSitemap: https://example.com/bad.xml")
            if "bad.xml" in url:
                return _mock_http_response(url, 404, b"Not Found")
            return _mock_http_response(url, 200, b"<html><body><a href='/broken'>Broken</a></body></html>")

        mock_fetch.side_effect = side_effect
        res = audit_discoverability("https://example.com/")

        self.assertGreater(len(res["findings"]), 0)
        for finding in res["findings"]:
            is_valid, err = FindingFactory.validate(finding)
            self.assertTrue(is_valid, f"Generated finding failed validation: {err}")
            self.assertTrue(len(finding["evidence"].strip()) >= 10, "Evidence must be non-empty and substantive")
            self.assertIn(finding.get("methodology"), ["Reach", "Read", "Extract", "Understand"])


if __name__ == "__main__":
    unittest.main()
